---
resource_types:
  - name: datetime-version
    type: registry-image
    source:
      repository: dcsg/datetime-version-resource


resources:
  - name: genversion
    type: datetime-version
  - name: compute-image-tools
    type: git
    source:
      uri: https://github.com/hopkiw/compute-image-tools.git
      branch: liamh_desc-2
  - name: guest-test-infra
    type: git
    source:
      uri: https://github.com/hopkiw/guest-test-infra.git
      branch: concourse-2

jobs:
  - name: generate-new-version
    plan:
      - put: genversion

  - name: build-debian-9
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-debian-9
        file: guest-test-infra/concourse/tasks/daisy-build-image.yml
        vars:
          wf: "image_build/debian/debian_9.wf.json"
          path: "gs://liamh-export/image_builds_ci/debian-9-v((.:version))/root.tar.gz"

  - name: build-debian-10
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-debian-10
        file: guest-test-infra/concourse/tasks/daisy-build-image.yml
        vars:
          wf: "image_build/debian/debian_10_fai.wf.json"
          path: "gs://liamh-export/image_builds_ci/debian-10-v((.:version))/root.tar.gz"

  - name: build-centos-6
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-centos-6
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/centos_6.wf.json"
          path: "gs://liamh-export/image_builds_ci/centos-6-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/CentOS-6.10-x86_64-bin-DVD1.iso"

  - name: build-centos-7
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-centos-7
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/centos_7_uefi.wf.json"
          path: "gs://liamh-export/image_builds_ci/centos-7-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/CentOS-7-x86_64-DVD-2003.iso"

  - name: build-centos-8
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-centos-8
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/centos_8_uefi.wf.json"
          path: "gs://liamh-export/image_builds_ci/centos-8-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/CentOS-8.2.2004-x86_64-dvd1.iso"

  - name: build-rhel-6
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-rhel-6
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/rhel_6.wf.json"
          path: "gs://liamh-export/image_builds_ci/rhel-6-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/rhel-server-6.10-x86_64-dvd.iso"

  - name: build-rhel-7
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-rhel-7
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/rhel_7_uefi.wf.json"
          path: "gs://liamh-export/image_builds_ci/rhel-7-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/rhel-server-7.8-x86_64-dvd.iso"

  - name: build-rhel-8
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        trigger: true
      - load_var: version
        file: genversion/version
      - task: daisy-build-rhel-8
        file: guest-test-infra/concourse/tasks/daisy-build-image-el.yml
        vars:
          wf: "image_build/enterprise_linux/rhel_8_uefi.wf.json"
          path: "gs://liamh-export/image_builds_ci/rhel-8-v((.:version))/root.tar.gz"
          iso: "gs://liamh-export/linux-build-resources/rhel-8.2-x86_64-dvd.iso"


  - name: publish-to-staging-debian-9
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-debian-9]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-debian-9
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/debian-9-v((.:version))/root.tar.gz"
          name: "debian-9-stretch-v((.:version))"
          wf: "image_publish/debian/debian_9.wf.json"

  - name: publish-to-staging-debian-10
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-debian-10]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-debian-9
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/debian-9-v((.:version))/root.tar.gz"
          name: "debian-9-stretch-v((.:version))"
          wf: "image_publish/debian/debian_9.wf.json"

  - name: publish-to-staging-centos-6
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-centos-6]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-centos-6
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/centos-6-v((.:version))/root.tar.gz"
          name: "centos-6-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/centos_6.wf.json"

  - name: publish-to-staging-centos-7
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-centos-7]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-centos-7
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/centos-7-v((.:version))/root.tar.gz"
          name: "centos-7-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/centos_7.wf.json"

  - name: publish-to-staging-centos-8
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-centos-8]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-centos-8
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/centos-8-v((.:version))/root.tar.gz"
          name: "centos-8-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/centos_8.wf.json"

  - name: publish-to-staging-rhel-6
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-rhel-6]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-rhel-6
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/rhel-6-v((.:version))/root.tar.gz"
          name: "rhel-6-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/rhel_6.wf.json"

  - name: publish-to-staging-rhel-7
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-rhel-7]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-rhel-7
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/rhel-7-v((.:version))/root.tar.gz"
          name: "rhel-7-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/rhel_7.wf.json"

  - name: publish-to-staging-rhel-8
    plan:
      - get: compute-image-tools
      - get: guest-test-infra
      - get: genversion
        passed: [build-rhel-8]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: publish-rhel-8
        file: guest-test-infra/concourse/tasks/daisy-publish-image.yml
        vars:
          path: "gs://liamh-export/image_builds_ci/rhel-8-v((.:version))/root.tar.gz"
          name: "rhel-8-stretch-v((.:version))"
          wf: "image_publish/enterprise_linux/rhel_8.wf.json"

  - name: image-validation-tests
    plan:
      - get: guest-test-infra
      - get: genversion
        passed: [publish-to-staging-debian-9, publish-to-staging-debian-10, publish-to-staging-centos-6, publish-to-staging-centos-7, publish-to-staging-centos-8, publish-to-staging-rhel-6, publish-to-staging-rhel-7, publish-to-staging-rhel-8]
        trigger: true
      - load_var: version
        file: genversion/version
      - task: validate-debian-9
        file: guest-test-infra/concourse/tasks/validate-image.yml
        vars:
          image_name: debian-9-stretch-v((.:version))
          image_project: liamh-export
