---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gcr.io/liamh-testing/daisy-with-creds, tag: latest}

run:
  path: /daisy
  args: ["-project=liamh-testing","-zone=us-west1-b","-var:installer_iso=((iso))","/workflows/((wf))"]
