---
platform: linux

image_resource:
  type: docker-image
  source: {repository: google/cloud-sdk, tag: latest}

run:
  path: gcloud
  args:
    - compute
    - images
    - create
    - --source-uri=((path))
    - --family=((family))
    - --description=((name)) built from ((path))
    - --project=((project))
    - ((name))
