---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

outputs:
  - name: build-id-dir

run:
  path: bash
  args:
  - -c
  - "date '+%s' | tee build-id-dir/build-id"
