---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

outputs:
  - name: build-id-dir

run:
  path: bash
  args:
  - -c
  - 'buildid=$(date "+%s"); echo "$buildid" | tee build-id-dir/build-id; touch build-id-dir/rhel-8-v${buildid}-root.tar.gz'
