---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox, tag: latest}

run:
  path: echo
  args:
    - this should do some tests on projects/((image_project))/global/images/((image_name))
